### ISSUE TITLE
Control over column order

### ISSUE THREAD

**Issue by joelstransky** [bradjasper/ImportJSON#11]
When using with the Trello api (haven't test with other sources) there doesn't seem to be control over column order.
I'm using `"/cards/dateLastActivity,/cards/name,/cards/desc,/cards/shortUrl"` as my queries but the columns still get rendered as `Datelastactivity`, `Desc`, `Name`, `Shorturl`

**Comment by colettaconsulting** [comment]
I'm experiencing the same issue - any suggested fixes would be greatly appreciated!

**Comment by bradjasper** [comment]
Don't believe there is currently a fix for this, but it's been added to potential enhancements.
