### ISSUE TITLE
Data imported incorrectly when multiple values refer to the same header

### ISSUE THREAD

**Issue by okun78** [bradjasper/ImportJSON#12]
When in the script are present different values for the same header (in my case more than an option for a product) it duplicates the row and misses some data.

For example this part of a json

![json](https://cloud.githubusercontent.com/assets/11423064/6595608/386a7444-c7ec-11e4-9033-4f7c8bbba0dc.png)

the result is the following

![sheet](https://cloud.githubusercontent.com/assets/11423064/6595614/44b414bc-c7ec-11e4-9ab9-f065deebd990.png)

**Comment by rockinghelvetica** [comment]
From here: http://blog.fastfedora.com/projects/import-json#ImportJSON it appears that the fix is line 286, but I've not regressed it to say that's the correct fix across the board.

        if (data[state.rowIndex]) {
          state.rowIndex++;
        }

**Comment by okun78** [comment]
Thanks a lot for your answer. I tried to apply the change you suggest, but the result, although it's better, is still not correct. Here it is:

![schermata 2015-07-07 alle 09 41 19](https://cloud.githubusercontent.com/assets/11423064/8541194/a0168ffe-248c-11e5-91c4-187426169bea.png)

**Comment by bradjasper** [comment]
I believe this is being addressed with https://github.com/bradjasper/ImportJSON/issues/38
