### ISSUE TITLE
Getting errors when pulling large amounts of data

### ISSUE THREAD

**Issue by snoopy82481** [bradjasper/ImportJSON#14]
I am getting SyntaxError: Unterminated string literal (line 132).  I am trying to pull data from http://eddb.io/archive/v3/stations.json in google docs using =ImportJSON("http://eddb.io/archive/v3/stations.json","","noInherit, noTruncate") it also gives me a separate error Internal error executing the custom function. when using =ImportJSON("http://eddb.io/archive/v3/systems.json","","noInherit, noTruncate").

**Comment by bradjasper** [comment]
If you are still getting this error, please reopen this issue, thanks.
