### ISSUE TITLE
introducing extra characters

### ISSUE THREAD

**Issue by vfulco** [bradjasper/ImportJSON#16]
Copy 'raw' version and save to goog sheets, tried the =ImportJSON() found in Gambill's medium story (https://medium.com/@paulgambill/how-to-import-json-data-into-google-spreadsheets-in-less-than-5-minutes-a3fede1a014a) and extra characters pop up giving an error.  --> =ImportJSON(“http://date.jsontest.com", "/date")").  Any attempt to manually fix func replicates the error. TIA.

**Comment by bradjasper** [comment]
If you are still experiencing this error, please reopen this issue.
