### ISSUE TITLE
Auto-update

### ISSUE THREAD

**Issue by avlysenko** [bradjasper/ImportJSON#19]
Hi!

Thx for your code!

I have question about auto-update.

Try run by timer this:
function myUpdate() {

var ss = SpreadsheetApp.getActiveSpreadsheet();
ss.setActiveSheet(ss.getSheetByName("AUPD"));

var testIt = ImportJSON("***");

 var cell = ss.getRange("A1");
 cell.setValue( testIt );

}

---

But result only in one cell A1.

---

How to properly do an automatic update on a timer?

**Comment by avlysenko** [comment]
Is it possible run ImportJSON from other function and paste result in cell?

**Comment by bradjasper** [comment]
Hello, this should be possible. Have you tried using the Logger to debug?

**Comment by xyzzy529** [comment]
See issue #49 as the updated version of this question.
