### ISSUE TITLE
Problems with underscore "_" in json attributes

### ISSUE THREAD

**Issue by oscarvesga** [bradjasper/ImportJSON#21]
Hi all,

I have problems when json attributes come with underscore. Example

`{
  "courses" :  {
    "request": {
       url:"https"
     },
    "course": { 
      "url":"http",
      "number: "0000",
      "number_id":"xxx1"
     }
  }
}`

When I used the ImportJSON function, I just can see 3 colums, not 4

**Comment by bradjasper** [comment]
Please try with the latest version and let me know if this is still an issue. Thanks!
