### ISSUE TITLE
Google sheets no longer has Tools > Script Editor. It now uses the "appsheet"

### ISSUE THREAD

**Issue by xanderoot** [bradjasper/ImportJSON#219]
title is the majority of it. Additionally when attempting to add the js to the app workplace it throws an error  
Exception: Attribute provided with no value: url
ImportJSONAdvanced	@ Json.gs:220
ImportJSON	@ Json.gs:71

**Comment by xanderoot** [comment]
was running the sheet out of an excel file, google removes access to script editor. converted to sheets format gave access

**Comment by oZeppy** [comment]
Did you find a solution?

**Comment by xanderoot** [comment]
I do not recall. If I found anything out I would have included it in the
ticket. I vaguely recall the issue being that it had something to do with
reading the file from an excel file in the Google doc directory vs a native
Google sheet
