### ISSUE TITLE
Import JSON stops working!

### ISSUE THREAD

**Issue by JuanFirmino** [bradjasper/ImportJSON#228]
Hello friends

I've been using this script for 2 years and yesterday (02/03/2022), it stopped working! I've done several tests, but it doesn't work, it just displays this message "Loading" (print).

Can you help me please
<img width="1176" alt="Captura de Tela 2022-03-03 às 11 21 32" src="https://user-images.githubusercontent.com/76651826/156588132-ebbe720d-5828-4611-9be3-f679699ffddc.png">

**Comment by SzilagyiR** [comment]
Same problem here ...

**Comment by SzilagyiR** [comment]
> Same here ...

Star working again now!

**Comment by axelgfelix** [comment]
Hello friends, unfortunately, I'm also having this "loading..." issue, any solutions? or just wait? I have a Google Workspace account.

**Comment by berevoescu** [comment]
Same here - I'm using this script for 3-4 years - no glitch.
I use it linked to a trigger that kicks in every hour.
It started to show this problem yesterday, somewhere between 4pm and 6pm PST.
Since nothing changed in the script itself it looks like something changed on the Google side.

**Comment by mbencho** [comment]
It's a global google docs issue. We can only wait till they fix it. 
https://support.google.com/docs/thread/153166088?hl=en&msgid=153387464

**Comment by berevoescu** [comment]
> It's a global google docs issue. We can only wait till they fix it. https://support.google.com/docs/thread/153166088?hl=en&msgid=153387464

Not sure I can see how this issue is related. There is no use of those Google API calls in the script. Could be an auth issue as someone suggested?
In my case saw some errors in the Execution panel yesterday evening, but right now the trigger does not even seem to call the script. It's pretty odd.

**Comment by axelgfelix** [comment]
Seems to be related, in the Google Thread, a user mentioned:

> Brad Jasper's ImportJSON function appears to be impacted by this issue as well. It would seem any call for web data is currently broken.
