### ISSUE TITLE
Update Formula Examples

### ISSUE THREAD

**Issue by EnGlamdring** [bradjasper/ImportJSON#25]
Your YouTube formula example is not longer valid. Once I switched it up to this it started working. 

=ImportJSON("http://date.jsontest.com", "/","noInherit,noTruncate,rawHeaders")

**Comment by jogorek** [comment]
Hi,

is it working for you? For me it shows an error... (#error)

**Comment by bradjasper** [comment]
Hello, other JSON feeds are still working—is it something specific with YouTube?
