### ISSUE TITLE
Anyone have problems with creating charts or aggregate functions on imported data?

### ISSUE THREAD

**Issue by ronhornbaker** [bradjasper/ImportJSON#27]
First of all, thanks for your code!

I'm unable to create a Chart, or perform simple aggregate functions like =SUM(A1:A10), on imported numeric json data in a Google Sheet. The Sheet is basically acting like the numbers are null, or zero, when charting or aggregates are involved, even though the numeric values are clearly there.

Even weirder: given values of 100 and 101 in cells A1 and A2, respectively, a formula in another cell like =A1+A2 correctly evaluates to 201, but =SUM(A1:A2) evaluates to 0.0.

Can anyone reproduce, or am I going crazy?

**Comment by ronhornbaker** [comment]
Solved it. All numerical data were getting transformed to strings unless the noTruncate flag was set.

The fix is to change these lines in the defaultTransform_ function:

```
if (!hasOption_(options, "noTruncate") && data[row][column]) {
  data[row][column] = data[row][column].toString().substr(0, 256);
}
```

to

```
if (!hasOption_(options, "noTruncate") && (typeof data[row][column]=='string')) {
  data[row][column] = data[row][column].toString().substr(0, 256); 
}
```

**Comment by ra4tx** [comment]
Hmm, I'm having the same issue, all numerics are written as text.  I tired this code change but that didn't seem to change the behavior of the function.  I'm at line 418 in version 1.2.1.  Anyone else had luck with this?  My work around is computing the =value() of every imported JSON data item.

**Comment by bradjasper** [comment]
Hello, converting your data to numbers should take care of this. If you're still experiencing this on the latest version please let me know.

**Comment by pabloab** [comment]
Duplicate of issue #7?
