### ISSUE TITLE
Move result to the right instead of below

### ISSUE THREAD

**Issue by visitdigital** [bradjasper/ImportJSON#28]
How would i move the result to the right of the cell instead of it going below?

**Comment by bradjasper** [comment]
Hello, currently this isn't supported by default. It may be possible with some kind of transpose operation.

**Comment by Trls250** [comment]
Realize this is old but for anyone interested going forward I was able to work around this using the QUERY function google sheets, this stack exchange question details the various workarounds:

https://webapps.stackexchange.com/questions/57540/can-i-use-column-headers-in-a-query

**Comment by AlFaMoDz** [comment]
I know it's still later than the comment above, but I managed to fix it using only TRANSPOSE

Example: `=TRANSPOSE(ImportJSON("http://date.jsontest.com", "/date", "noInherit, noTruncate"))`
