### ISSUE TITLE
Replace script for IMPORTXML (for larger xml files)

### ISSUE THREAD

**Issue by diegocgaona** [bradjasper/ImportJSON#29]
Hi,

I want to import a Google Shopping XML to a Google Spreadsheet, but Google Spreadsheet shows a error:

Error Resource at url contents exceeded maximum size.

I need to import the data (and update it each 6 hours) and I don't know how with this error.

A example of what I using is this:

=IMPORTXML("http://avambu.xtechcommerce.com/datafeeds/google_shopping","//channel/item")
But with a larger XML.

There is a script or another solution for this? Your script will work for this type of file?

Thanks!

**Comment by bradjasper** [comment]
Hello, this is for the ImportJSON project. ImportXML docs can be found here https://support.google.com/docs/answer/3093342?hl=en
