### ISSUE TITLE
Missing First line of data

### ISSUE THREAD

**Issue by Pyrosfr** [bradjasper/ImportJSON#32]
Hello

I've tried the script on a sample json source : http://api.geonames.org/postalCodeLookupJSON?postalcode=6600&country=AT&username=demo wich is also attached to this post

According to the source, i expect to get the first line with code  70805
`"postalcodes":[{"adminCode2":"708","adminCode3":"70805","adminName3":"Breitenwang"...`
But on my spreadsheat, i've got : 
`Admincode2	Admincode3	Adminname3	Admincode1

708	70806	Ehenbichl	07

708	70820	Lechaschau	07

708	70822	Musau	07`

the first line is missing.
I've got the same issue with others json database export.

Thx
[test.txt](https://github.com/fastfedora/google-docs/files/889463/test.txt)

**Comment by mdmclean88** [comment]
I have had this problem for a while and just found a solution in the comments on the fastfedora website.

On line 286-288

replace:
`
if (i > 0 && data[state.rowIndex]) {
          state.rowIndex++;
        }`

With:

` 
if (data[state.rowIndex]) {
          state.rowIndex++;
        }`

And voila it works.

Credit to Brian Lewis
http://blog.fastfedora.com/projects/import-json#comment-20433

**Comment by bradjasper** [comment]
This should be fixed in the latest version.
