### ISSUE TITLE
Having issues importing a feed properly.

### ISSUE THREAD

**Issue by jgilf** [bradjasper/ImportJSON#37]
Hi all, 

I'm currently trying to import a feed that looks like this:
 
https://pastebin.com/raw/qB4Ysayv 

I want each new entry (i.e. W18040926, 70006557V in this example) to be imported as a new row. However, no matter what I try to do, the data keeps importing as one single row.

Am I missing something really obvious?

**Comment by bradjasper** [comment]
Hello, I think typically the imports work better with arrays of objects. The JSON data here has a few different schemas. Is it possible to get them all looking similar?
