### ISSUE TITLE
Data updates

### ISSUE THREAD

**Issue by ddollar** [bradjasper/ImportJSON#4]
My doc never appears to be pulling the value again from a URL past the first time. How can I make it refresh periodically?

**Comment by bradjasper** [comment]
Hello, this is an older issue and we are doing some cleaning up. If it is still relevant, please reopen. Thanks!

**Comment by TriMoon** [comment]
Can't use cells with reference to <code>NOW()</code> etc as an argument to custom functions anymore...
See: https://developers.google.com/apps-script/guides/sheets/functions#arguments
