### ISSUE TITLE
For Excel ?

### ISSUE THREAD

**Issue by mr-aleks** [bradjasper/ImportJSON#40]
Hello,
I really like your project, I use it for my calculations. But I can not always use google spreadsheet , can you rewrite this code for an ms excel in the language of the vba?
Or how can me run your code in excel?

**Comment by bradjasper** [comment]
Hello, unfortunately this is only for Google Sheets—there are no plans to support Excel. These resources may be able to help https://social.msdn.microsoft.com/Forums/office/en-US/9074e7f4-dd5b-44c7-8cd6-d7db77c55bf7/importing-json-into-excel?forum=exceldev
