### ISSUE TITLE
Rate Request Limiting Loading....

### ISSUE THREAD

**Issue by justinpfister** [bradjasper/ImportJSON#41]
I'm using =ImportJson() to populate over 5000+ cells and it works really well.  Problem is.. i'm often stuck on a sheet where there's 1000's of cells are in "Loading..." My data isn't very fast changing and only needs to be refreshed every 72 hours (or even less). Is there any way to enforce this sort of behavior?

Additional Information:  The server managing the JSON responses runs very fast and most of the time the response is cached. I think the problem is more due to Google Sheets managing 1000's of ImportJSON() commands on a single page. 

Any insight would be helpful. Thank you.

**Comment by justinpfister** [comment]
https://developers.google.com/apps-script/reference/cache/  ??

**Comment by justinpfister** [comment]
I had to do 2 things to make this work.. 
1) added a MD5 function for easily creating a cache_key:
var cache_key = MD5(url + query + parseOptions); 

2) use the cache utility exactly as shown in the example code.

**Comment by mchoboter** [comment]
I have run into this problem before as well with cells just hanging as "Loading..." I'd be curious to see exactly what your changes look like.

**Comment by saurfang** [comment]
I have used the following to add a random wait to the `ImportJSON` function as a workaround in rate limiting:

```js
  var milliseconds = Math.floor(((Math.random() * 5) + 0) * 1000);
  
  Utilities.sleep(milliseconds);
```
