### ISSUE TITLE
Querying a specific field doesn't work

### ISSUE THREAD

**Issue by eminogrande** [bradjasper/ImportJSON#43]
I've tried both queries. One with "/title" and one without. The one with "/title" only returns that there is a `parsing error`.

With error:
`=ImportJSON("https://mysafeinfo.com/api/data?list=bestnovels&format=json&rows=20&alias=cnt=count,avg=average_rank,tt=title,au=author,yr=year", "/title")`

Without error:
`=ImportJSON("https://mysafeinfo.com/api/data?list=bestnovels&format=json&rows=20&alias=cnt=count,avg=average_rank,tt=title,au=author,yr=year")`

**Comment by bradjasper** [comment]
Hello, I responded via email but both of these queries work in the default spreadsheet—so I think it might be something with the ImportJSON script itself being behind.
