### ISSUE TITLE
How to sort by columns and not get refreshed

### ISSUE THREAD

**Issue by adriadrop** [bradjasper/ImportJSON#44]
Script is great and easy to use. Problem I have is that whenever I click to sort on some column API I am using to get data gets refreshed and I get data sorted the same as before.

Wondering how could I solve this, maybe to remove onLoad and have on some button clicked that loads the data, or maybe to keep sort somehow on refresh?

**Comment by bradjasper** [comment]
Hello, unfortunately I'm not sure the best way to handle this. The sorting might have to be done in ImportJSON first, or the data fetched and normalized to text and then sorted. The first option is a bit harder, and the second option would stop future update—so not ideal. If anyone is interested in building this (or has a better way) I'd consider adding it.

**Comment by mchoboter** [comment]
as a possibility you can use the =Sort formula around the importJSON and that will sort whatever column you need

**Comment by bradjasper** [comment]
Thanks for the tip @mchoboter!
