### ISSUE TITLE
Authentication issues with ImportJSON

### ISSUE THREAD

**Issue by mamanoy** [bradjasper/ImportJSON#46]
Hi,

I am trying to import JSON from URL into Google Sheets but I am getting an "Error code 401. Truncated server response: HTTP Digest: Access denied" despite using "user=bob&apikey=xxxx". Could this be because authentication is asked in a "pop-up" window? See attached.

Thanks,

Martin
![screenshot1-popup](https://user-images.githubusercontent.com/32291848/30848565-1e3e0b3a-a2d2-11e7-8d65-88b9bb2d6977.jpeg)

**Comment by bradjasper** [comment]
Hello, to use username/password you can use the function ImportJSONBasicAuth. See here: https://github.com/bradjasper/ImportJSON/blob/master/ImportJSON.gs#L222 for more info.

**Comment by mamanoy** [comment]
Hi Brad,

Thanks for your reply.

I’ve tried using ImportJSONBasicAuth but i still get an error. See attached screenshot.

Thanks,

Martin
On 27 Sep 2017, at 2:56 AM, Brad Jasper <notifications@github.com> wrote:

Closed #46 <https://github.com/bradjasper/ImportJSON/issues/46>.
