### ISSUE TITLE
using concatenate causes "invalid parameter" error (%20 space in parameters)

### ISSUE THREAD

**Issue by tboooe** [bradjasper/ImportJSON#53]
I am trying to use concatentate to create the input parameters with a variable for the importJSON function. The concatenated string looks and works fine if I copy it into the importJSON function but if I reference the string as part of the function or use concatenate in the function I get an invalid argument error.

Here is the concatenate string. Cell I7 is the date. For example 2017-11-27.

=concatenate("""https://www.alphavantage.co/query?function=TIME_SERIES_DAILY&symbol=MSFT&apikey=demo""",",","""","/Time Series (Daily)/",I7,"/4. close""", ", ","""noHeaders""")

Here is the output string with the date variable:

"https://www.alphavantage.co/query?function=TIME_SERIES_DAILY&symbol=MSFT&apikey=demo","/Time Series (Daily)/2017-11-27/4. close", "noHeaders"

This works if I copy the concatenate output string manually into the function:

=importJSON("https://www.alphavantage.co/query?function=TIME_SERIES_DAILY&symbol=MSFT&apikey=demo","/Time Series (Daily)/2017-11-27/4. close", "noHeaders")

These dont work:

=importJSON(concatenate("""https://www.alphavantage.co/query?function=TIME_SERIES_DAILY&symbol=MSFT&apikey=demo""",",","""","/Time Series (Daily)/",I7,"/4. close""", ", ","""noHeaders"""))

=importJSON(K9) >> K9 is cell where the concatenate function is

**Comment by mchoboter** [comment]
When you are concatenating the date it may be using a number rather than the date itself. I break up the date into its separate pieces when I need to include it. Also, you don't need the concatenate function. You can use an & symbol to accomplish the same thing.

In my sheet I have broken the date into separate columns (G1,H1,F1)
As an example
So my web address :
=http://www.fantasylabs.com/api/lines/4/Anaheim%20Ducks/11-29-2017/

Becomes for the importjson:
="http://www.fantasylabs.com/api/lines/4/Anaheim%20Ducks/"&G1&"-"&H1&"-"&F1&"/"

**Comment by tboooe** [comment]
Thank you for the reply but I dont think its a date issue because I get the same error when not using the date. The error  I am seeing has to something to do with the spaces in the second parameter.  The error references line 212 in the code which is  var jsondata = UrlFetchApp.fetch(url, fetchOptions);

The spaces in the second parameter is being read as %20.  The weird thing is if the directly enter the same parameter into the function it works fine.

Here is another query I tried without a date that also results in the same error:
=importJSON("https://www.alphavantage.co/query?function=TIME_SERIES_DAILY&symbol=MSFT&apikey=demo","/Meta Data/2. Symbol", "noHeaders")

**Comment by mchoboter** [comment]
I tried that formula as it is and it works for me. I added as a reference and it worked as well. attached a picture

![image](https://user-images.githubusercontent.com/8965153/33394338-3983c646-d4ff-11e7-9ce3-a8dd92627f29.png)

**Comment by tboooe** [comment]
Can you try this as the reference cell:
=concatenate("""/Meta Data/","2. Symbol""")

**Comment by mchoboter** [comment]
ahh, that is returning 

"/Meta Data/2. Symbol"

which is including the " on the front and end. You have extra " in the formula

Try this
=concatenate("/Meta Data/","2. Symbol")

**Comment by tboooe** [comment]
BINGO!  Thank you VERY VERY much!  I've racking my brain on this all morning.

**Comment by mustavanov** [comment]
this issue took me while before figure out how to solve it , specially the date format to include it in the importjson request , i had to change all my "{" to "%7B" and "}" to "%7D" and the problem with the date when you include , it's converted to numbers , so the workaround for me in google sheets is to convert it to text automatically in another cell using the function ISTEXT in google sheet. for example : A1 has a date format i need , so in C1 i use the function =ISTEXT(a1) and i use C1 in CONCATENATE
