### ISSUE TITLE
ImportJSONBasicAuth = Invalid argument

### ISSUE THREAD

**Issue by uado64** [bradjasper/ImportJSON#56]
Hello guys,

I am trying to import a JSON file with Basic Authentication from this:
=ImportJSONBasicAuth("https://apirest.atinternet-solutions.com/data/v2/json/getMaxDate?&space={s:547656}","login","password","","")

It looks like the format of this URL doesn't work as other URLs do work. What can I do to make it work? Should I encode it to get rid of the curly brackets and the single quotes?

Thanks.

**Comment by ralphilius** [comment]
There is `?&` between `getMaxDate` and `space={s:547656}`. Shouldn't it just `?`?

Also, you can try encode your url

**Comment by uado64** [comment]
Hi there,

the "?&" is fine, we have managed to encode the URL and it now works perfectly fine.

Cheers.
