### ISSUE TITLE
Rows missing when parsing some arrays

### ISSUE THREAD

**Issue by fastfedora** [bradjasper/ImportJSON#8]
[This data set](http://jsonviewer.stack.hu/#http://europeana.eu/api//v2/search.json?wskey=ISXVIQBYBQ&query=*:*&start=1&rows=0&profile=facets) is not returning all of its rows when queried with the query `“/facets/name,/facets/fields/label,/facets/fields/count”`.

The problem is that the `/facets/fields` is skipping rows from 'name:LANGUAGE', 'name:TYPE' and 'name:YEAR' among others. It is also merging in the wrong value for `/facets/name`. 

[View this sample spreadsheet](https://docs.google.com/spreadsheets/d/18CBvDafs8t8vSc0Y88gx12C-WAbSTrgLDgRk97tTXl4/edit?usp=sharing) that uses the following call:

```
=ImportJSON(“http://europeana.eu/api//v2/search.json?wskey=ISXVIQBYBQ&query=*:*&start=1&rows=0&profile=facets”, 
            “/facets/name,/facets/fields/label,/facets/fields/count”, 
            “noTruncate”)`
```

**Comment by kenorb** [comment]
It seems to happen for most of the feeds. The first row is always ignored.

Example feeds:

    http://gdata.youtube.com/feeds/api/standardfeeds/most_popular?v=2&alt=json
    https://api.github.com/repos/mycognitive/ads/issues

**Comment by myktra** [comment]
I'm observing this as well. First row ignored unless the number of objects in the array returned by the feed is 1. Even on something as simple as the following JSON - only the second row is returned.

    [{"Amount":"8,996.00"},{"Amount":"3,802.00"}]

    Amount
    3,802.00

**Comment by Zyles** [comment]
Suffering from this bug:

```
=importJSON("https://api.guildwars2.com/v1/recipe_details.json?recipe_id=515", "/ingredients")
```

There are 3 ingredients, and output is 2.

**Comment by macolo** [comment]
I tracked it down to https://github.com/mhawksey/google-docs/blob/master/scripts/ImportJSON/Code.gs#L286

(the 'i > 0' part)

which I removed and it started to work.

Here is my test case in GAS:

https://gist.github.com/macolo/6834dee326547f93194a

**Comment by lawsonshanks** [comment]
Based off of macolo's answer, got it working by replacing

https://github.com/mhawksey/google-docs/blob/master/scripts/ImportJSON/Code.gs#L286

 with 

**"if (i  >=  0 && data[state.rowIndex]) {"**

**Comment by kenorb** [comment]
Good catch @macolo. Did the blind fix and PR #1, please test. Hopefully it will work:)

**Comment by fastfedora** [comment]
@kenorb You can actually remove `i >= 0 &&`, since `i` is always greater than 0. Until I have time to analyze why I put this test in there to begin with, I'm leaving it in the codebase and letting people who are experiencing this specific problem remove it manually.

**Comment by ryantheleach** [comment]
I ran into this bug, and fixed it the same way. Would be good to merge it in..

**Comment by Artanis** [comment]
@ryantheleach :+1:

**Comment by sknepal** [comment]
Same as @ryantheleach. Spent too much time tracking it down, and when I finally solved it (the same way), I saw this issue. Should have checked out the issues earlier. Maybe its time to merge or maybe, at least a sort of hint in the comments / readme?

**Comment by bradjasper** [comment]
This was merged in https://github.com/bradjasper/ImportJSON/pull/18
